//generated by 'g controller items' in terminal

//deps
import { Controller, Get, Post, Put, Delete, Body, Param } from '@nestjs/common';
import { CreateItemDto } from './dto/create-item.dto';
import { ItemsService } from './items.service';
import { Item } from './interfaces/item.interface';



//decoraters for endpoints instead of routers
@Controller('items')
export class ItemsController {
    constructor(private readonly itemsService: ItemsService) {}


    @Get()
    findAll(): Promise<Item[]> {
        return this.itemsService.findAll();
    }

    @Get(':id')
    findOne(@Param('id') id): Promise<Item> {
        return this.itemsService.findOne(id); 
    }


    @Delete(':id')
    delete(@Param('id') id): Promise<Item> {
        return this.itemsService.delete(id); 
    }

    @Post()
    create(@Body() createItemDto: CreateItemDto): Promise<Item> {
        //create dto
        return this.itemsService.create(createItemDto); 
    }

    @Put(':id')
    update(@Body() updateItemDto: CreateItemDto, @Param('id') id): Promise<Item> {
        return this.itemsService.update(id, updateItemDto);
    }

}




